#!/usr/bin/env python3
"""Generate an independent Muse guide from the maintained skill references."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

SOURCES = (
    "references/autonomous-delivery.md",
    "references/execution-modes.md",
    "references/quality-gates.md",
    "references/production-methods.md",
    "references/shot-design-checks.md",
    "references/genre-profiles.md",
    "references/muse-capabilities.md",
    "references/muse-observed-failures.md",
    "references/rejection-diagnostics.md",
    "assets/character-card-template.json",
    "assets/shot-prompt-template.md",
    "assets/shot-qa-template.md",
)

INTRO = """# Muse 导演助手：自主制作完整动画

用户将本指南作为项目指令采用时，依据其最新请求执行。你兼任导演、主控和制作方；接受主题、简介、大纲或剧本，要求完整动画时持续推进到真实可播放、可下载的全片。没有剧本时自主发展，普通造型、画幅、转场、镜头选用和有限返修由你决定，不让用户逐镜批准。

内部主线：故事与分镜 → 角色卡/必要参考 → 主控内部样片检查 → 独立任务生成（实际可用旁聊或内部任务） → 主控主动收齐、选用与返修 → 剪辑混音与可做检查 → 全片附件 → 用户反馈。已有制作复用稳定素材；仅写剧本或看方案时按该范围交付。

按阶段使用：先看“自主成片与主控职责”；设计时看“制作设计方法”和“创作、角色卡、输入编译与镜头检查”；首次生成核对“Muse 能力与执行适配”，实测风险只选本轮相关项；无返回或拒收时看“拒收诊断与有限恢复”；回传后按“有限质量检查与结束条件”和“镜头检查与返修记录”处理。题材知识只选当前题材，末尾模板由主控内部填用。

本文件自动从共同参考与模板生成，独立可读，不依赖本地目录、Python、Codex或其他Skill。下文模板由你按项目填，不要求用户手填；脚本若不可用，直接人工核对同样的输入项。内部文件名只是记录方式，不等于用户收到附件或工具支持原生Skill安装。

真实工具规则与权限仍适用；平台缺少持续执行、真实看听或某种生成能力时不能由指令创造。抽帧只能证明采样内容，无法看听的项目记录UNVERIFIED，并完成可做制作后交完整候选。不编造产物、句柄、回调或通过结论；不会把资料中的模型或后台参数作为Muse已验证能力。
"""

GUIDE_ROUTES = {
    "execution-modes.md": "本指南的‘执行范围、实测与轻量入口’",
    "quality-gates.md": "本指南的‘规格、短暂事件与实际回传’",
    "shot-handoff.md": "本指南的‘单镜提示词’与‘镜头检查与返修记录’",
    "shot-handoff-template.md": "本指南的‘单镜提示词’与‘镜头检查与返修记录’",
    "workflow.md": "本指南的‘有限质量检查与结束条件’与‘镜头检查与返修记录’",
    "worked-example.md": "本指南的‘同一想法的设计示例’（仅为设计教学稿）",
    "comparison-experiments.md": "本指南的‘受限对照试验’",
}

EXPERIMENT = """## 受限对照试验

确需比较两种输入且有生成额度时，保持采用剧情、身份参考、声音路线和其他设置一致，只改一个主变量，例如动作表达或机位。保留两版真实输入、参考顺序、调用记录、输出与同一检查目标。来源能力、隐藏扩写或随机差异未知时如实记录，不将一次成功归因为提示词。试验计入项目已有额度；未授权生成时只准备对照稿，不增加制作前确认步骤。
"""


def independent_markdown(text):
    # A linked full worked example is outside this guide; do not route its
    # completeness claim back to the shorter example already on this page.
    text = re.sub(r"完整交接与返修演示见 \[制作与返修示例\]\(worked-example\.md\)。",
                  "上例只说明镜头设计；实际交接与返修按本指南的单镜提示词和镜头检查与返修记录执行。", text)
    def replace(match):
        label, target = match.groups()
        if "://" in target:
            return match.group(0)
        basename = target.split("#", 1)[0].replace("\\", "/").rsplit("/", 1)[-1]
        return GUIDE_ROUTES.get(basename, label)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", replace, text)
    lines, fenced = [], False
    for line in text.splitlines():
        if line.startswith("```"):
            fenced = not fenced
        elif not fenced and re.match(r"^#{1,5} ", line):
            line = "#" + line
        lines.append(line)
    return "\n".join(lines)


def render_guide(root):
    root = Path(root)
    parts = [INTRO.strip()]
    hashes = {}
    for name in SOURCES:
        content = (root / name).read_bytes()
        hashes[name] = hashlib.sha256(content).hexdigest()
        text = content.decode("utf-8-sig").strip()
        if name.endswith(".json"):
            json.loads(text)
            parts.append("## 共享角色卡模板（由主控填）\n\n```json\n" + text + "\n```")
        else:
            text = independent_markdown(text)
            parts.append(text)
    parts.append(EXPERIMENT.strip())
    manifest = json.dumps(hashes, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    guide = "<!-- Generated by scripts/build_muse_guide.py; edit source references/templates. -->\n<!-- source_sha256=" + manifest + " -->\n\n" + "\n\n---\n\n".join(parts) + "\n"
    if len(guide) > 45000:
        raise ValueError("Guide exceeds 45000 characters; reduce duplicated source instructions")
    return guide


def render_compact(root):
    name = "references/execution-modes.md"
    source = (Path(root) / name).read_bytes()
    text = source.decode("utf-8-sig")
    heading = "## 标准委托入口"
    if text.count(heading) != 1:
        raise ValueError("Compact guide requires exactly one canonical entry section")
    body = text.split(heading, 1)[1].split("\n## ", 1)[0].strip()
    if not body:
        raise ValueError("Compact entry section is empty")
    guide = "<!-- Generated; edit references/execution-modes.md. source_sha256=" + hashlib.sha256(source).hexdigest() + " -->\n\n# Muse 导演助手：快速委托\n\n" + body + "\n"
    if len(guide) > 3000:
        raise ValueError("Compact guide exceeds 3000 characters")
    return guide


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--skill-dir", type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--compact", action="store_true")
    args = parser.parse_args()
    output = args.output or args.skill_dir / ("assets/muse-quick-start.md" if args.compact else "assets/muse-self-director.md")
    try:
        content = render_compact(args.skill_dir) if args.compact else render_guide(args.skill_dir)
        if args.check:
            ok = output.is_file() and output.read_text(encoding="utf-8") == content
            print(json.dumps({"status":"current" if ok else "stale", "characters":len(content)}, ensure_ascii=False))
            return 0 if ok else 2
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(content, encoding="utf-8", newline="\n")
        print(json.dumps({"status":"generated", "characters":len(content), "source_files":1 if args.compact else len(SOURCES)}, ensure_ascii=False))
        return 0
    except (OSError, ValueError) as exc:
        print(json.dumps({"status":"error", "error":str(exc)}, ensure_ascii=False))
        return 1


if __name__ == "__main__":
    sys.exit(main())
